eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka:123456789@localhost:8761/eureka/}
  instance:
    preferIpAddress: true
    # This allows multiple localhost instances to be registered with eureka to simulate two different zones.
    instance-id: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

# Sets default logging for logback
logging:
  level:
    root: INFO

# Execution delay
execution:
  delayInSeconds: 0 # Override this java -jar xxx.jar --execution.delayInSeconds=30